-- COMPLETE SCHEMA SYNC FOR CATCHA CRM
-- Run this ONCE in Supabase SQL Editor: https://supabase.com/dashboard/project/anawatvgypmrpbmjfcht/sql/new
-- This ensures all tables have columns matching src/types.ts

-- ============================================================
-- BASE COLUMNS (All tables need these)
-- ============================================================

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE users ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS manager_id UUID;
ALTER TABLE users ADD COLUMN IF NOT EXISTS team TEXT;

-- accounts
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS employee_count INTEGER;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS tier TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS logo TEXT;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS address JSONB;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS commission_rate NUMERIC;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS custom_data JSONB;

-- contacts
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS address JSONB;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS custom_data JSONB;

-- leads
ALTER TABLE leads ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS company TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS campaign_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS estimated_value NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS address JSONB;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_contact_date TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS commission_rate NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_to_deal_id UUID;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_by TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS custom_data JSONB;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS temperature TEXT;

-- deals
ALTER TABLE deals ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE deals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE deals ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contact_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS stage TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS probability NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS expected_close_date DATE;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS assignee_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS stage_entry_date TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS campaign_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS commission_rate NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS commission_amount NUMERIC;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS lead_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS won_at TIMESTAMPTZ;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS created_account_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS created_contact_id UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS custom_data JSONB;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS notes TEXT;

-- tasks
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS related_to_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS related_to_type TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS related_entity_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS related_entity_type TEXT;

-- campaigns
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS budget NUMERIC;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS spent NUMERIC;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS revenue NUMERIC;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS revenue_generated NUMERIC;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS leads_generated INTEGER;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS expected_cpl NUMERIC;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS target_audience TEXT;
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS template_id UUID;

-- tickets
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS ticket_number TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS requester_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS assignee_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS priority TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS sla_deadline TIMESTAMPTZ;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS messages JSONB;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS internal_notes JSONB;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS custom_data JSONB;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS related_to_id UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS related_to_type TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

-- calendar_events
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS related_to_type TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS related_to_id UUID;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS priority TEXT;
ALTER TABLE calendar_events ADD COLUMN IF NOT EXISTS is_all_day BOOLEAN;

-- communications
ALTER TABLE communications ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE communications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE communications ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS direction TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS related_to_type TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS related_to_id UUID;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS outcome TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS next_step TEXT;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS next_follow_up_date TIMESTAMPTZ;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE communications ADD COLUMN IF NOT EXISTS duration TEXT;

-- products
ALTER TABLE products ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE products ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_price NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate NUMERIC;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_level INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reorder_point INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS reorder_quantity INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS specifications TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dimensions JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS manufacturer TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier_sku TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_months INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS warranty_details TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE products ADD COLUMN IF NOT EXISTS custom_fields JSONB;

-- services
ALTER TABLE services ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE services ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE services ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS billing_cycle TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS unit_price NUMERIC;
ALTER TABLE services ADD COLUMN IF NOT EXISTS cost_price NUMERIC;
ALTER TABLE services ADD COLUMN IF NOT EXISTS tax_rate NUMERIC;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE services ADD COLUMN IF NOT EXISTS duration_hours INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS duration_minutes INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS prerequisites TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS deliverables TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS skills_required JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS crew_size INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS equipment_needed JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sla_response_hours INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sla_completion_days INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS quality_checklist JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS images JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS custom_fields JSONB;

-- quotes
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quote_number TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS deal_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS issue_date DATE;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS expiry_date DATE;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS line_items JSONB;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS subtotal NUMERIC;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS tax_total NUMERIC;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS terms TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS accepted_by TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS superseded_by UUID;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS version INTEGER;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS valid_until DATE;

-- invoices
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_number TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS deal_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS quote_id UUID;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS payment_status TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS issue_date DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_date DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS line_items JSONB;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS subtotal NUMERIC;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_total NUMERIC;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS terms TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS credits JSONB;

-- subscriptions
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS billing_cycle TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS next_bill_date DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS items JSONB;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS auto_generate_invoice BOOLEAN;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_invoice_id UUID;

-- crews
ALTER TABLE crews ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE crews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE crews ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS leader_id UUID;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS member_ids JSONB;
ALTER TABLE crews ADD COLUMN IF NOT EXISTS color TEXT;

-- zones
ALTER TABLE zones ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE zones ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE zones ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS color TEXT;

-- jobs
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_number TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS subject TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS assignee_id UUID;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS crew_id UUID;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_type TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS priority TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS zone TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS estimated_duration INTEGER;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS scheduled_date TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS scheduled_end_date TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lat NUMERIC;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lng NUMERIC;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_fields JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS swms_signed BOOLEAN;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS completion_signature TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS evidence_photos JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS bom JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS invoice_id UUID;

-- equipment
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS barcode TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS condition TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS last_service_date DATE;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS next_service_date DATE;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS purchase_price NUMERIC;

-- inventory_items
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS warehouse_qty INTEGER;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS reorder_point INTEGER;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS unit_price NUMERIC;

-- purchase_orders
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS po_number TEXT;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS supplier_id UUID;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS items JSONB;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS total NUMERIC;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS linked_job_id UUID;

-- bank_transactions
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS match_confidence TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS matched_to_id UUID;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS matched_to_type TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS reconciled BOOLEAN;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS reconciled_at TIMESTAMPTZ;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS reconciled_by TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS bank_reference TEXT;
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS notes TEXT;

-- expenses
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vendor TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_url TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS notes TEXT;

-- reviews
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS author_name TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS rating INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS platform TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS replied BOOLEAN;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reply_content TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS replied_at TIMESTAMPTZ;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS job_id UUID;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS account_id UUID;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS sentiment TEXT;

-- referral_rewards
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS referrer_id UUID;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS referred_lead_id UUID;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS reward_amount NUMERIC;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS payout_date DATE;
ALTER TABLE referral_rewards ADD COLUMN IF NOT EXISTS notes TEXT;

-- inbound_forms
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS fields JSONB;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS submit_button_text TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS success_message TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS target_campaign_id UUID;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS submission_count INTEGER;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS conversion_rate NUMERIC;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE inbound_forms ADD COLUMN IF NOT EXISTS embed_code TEXT;

-- chat_widgets
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS page TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS bubble_color TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS welcome_message TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS routing_user_id UUID;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS conversations INTEGER;
ALTER TABLE chat_widgets ADD COLUMN IF NOT EXISTS avg_response_time INTEGER;

-- calculators
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS base_rate NUMERIC;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS usage_count INTEGER;
ALTER TABLE calculators ADD COLUMN IF NOT EXISTS lead_conversion_rate NUMERIC;

-- automation_workflows
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS trigger JSONB;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS nodes JSONB;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS execution_count INTEGER;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS last_run_at TIMESTAMPTZ;
ALTER TABLE automation_workflows ADD COLUMN IF NOT EXISTS category TEXT;

-- webhooks
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS method TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS headers JSONB;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS trigger_event TEXT;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS last_triggered_at TIMESTAMPTZ;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS success_count INTEGER;
ALTER TABLE webhooks ADD COLUMN IF NOT EXISTS failure_count INTEGER;

-- industry_templates
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS target_entity TEXT;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS sections JSONB;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
ALTER TABLE industry_templates ADD COLUMN IF NOT EXISTS version INTEGER;

-- conversations
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS participant_ids JSONB;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS is_system BOOLEAN;

-- chat_messages
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS conversation_id UUID;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS sender_id UUID;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS content TEXT;

-- notifications
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read BOOLEAN;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS link TEXT;

-- documents
ALTER TABLE documents ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE documents ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_type TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_size TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS related_to_type TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS related_to_id UUID;

-- audit_log
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS entity_id UUID;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS previous_value TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS new_value TEXT;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS batch_id UUID;

-- payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS invoice_id UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount NUMERIC;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reference TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;

-- warehouses
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS org_id UUID;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS owner_id UUID;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS is_default BOOLEAN;

-- organizations
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS settings JSONB;

-- ============================================================
-- COMPLETION MESSAGE
-- ============================================================
SELECT 'Schema sync complete! All columns added.' AS result;
