-- ============================================
-- FIX NOT NULL CONSTRAINTS
-- Run this in Supabase SQL Editor
-- Generated: 2026-02-08
-- ============================================
-- Problem: COMPLETE_SCHEMA_FIX.sql added NOT NULL to optional fields
-- Solution: Drop NOT NULL from all columns that should be nullable

-- ACCOUNTS
ALTER TABLE accounts ALTER COLUMN address DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN custom_data DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN logo DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN city DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN state DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN email DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN industry DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN website DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN employee_count DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN avatar DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN tier DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN revenue DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN owner_id DROP NOT NULL;
ALTER TABLE accounts ALTER COLUMN commission_rate DROP NOT NULL;

-- CONTACTS
ALTER TABLE contacts ALTER COLUMN address DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN custom_data DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN company DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN avatar DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN title DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN email DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN mobile DROP NOT NULL;
ALTER TABLE contacts ALTER COLUMN department DROP NOT NULL;

-- LEADS
ALTER TABLE leads ALTER COLUMN address DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN custom_data DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN company DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN email DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN source DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN campaign_id DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN estimated_value DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN avatar DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN last_contact_date DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN commission_rate DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN converted_to_deal_id DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN converted_at DROP NOT NULL;
ALTER TABLE leads ALTER COLUMN converted_by DROP NOT NULL;

-- DEALS
ALTER TABLE deals ALTER COLUMN custom_data DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN contact_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN stage_entry_date DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN campaign_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN commission_rate DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN commission_amount DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN lead_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN won_at DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN created_account_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN created_contact_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN expected_close_date DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN assignee_id DROP NOT NULL;
ALTER TABLE deals ALTER COLUMN avatar DROP NOT NULL;

-- TASKS
ALTER TABLE tasks ALTER COLUMN description DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN assignee_id DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN due_date DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN related_to_id DROP NOT NULL;
ALTER TABLE tasks ALTER COLUMN related_to_type DROP NOT NULL;

-- CALENDAR_EVENTS
ALTER TABLE calendar_events ALTER COLUMN description DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN end_time DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN location DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN related_to_type DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN related_to_id DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN priority DROP NOT NULL;
ALTER TABLE calendar_events ALTER COLUMN is_all_day DROP NOT NULL;

-- CAMPAIGNS
ALTER TABLE campaigns ALTER COLUMN budget DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN spent DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN revenue DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN revenue_generated DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN leads_generated DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN start_date DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN end_date DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN description DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN expected_cpl DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN target_audience DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN template_id DROP NOT NULL;
ALTER TABLE campaigns ALTER COLUMN type DROP NOT NULL;

-- TICKETS
ALTER TABLE tickets ALTER COLUMN description DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN requester_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN sla_deadline DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN messages DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN internal_notes DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN custom_data DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN related_to_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN related_to_type DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN assignee_id DROP NOT NULL;

-- PRODUCTS
ALTER TABLE products ALTER COLUMN sku DROP NOT NULL;
ALTER TABLE products ALTER COLUMN code DROP NOT NULL;
ALTER TABLE products ALTER COLUMN description DROP NOT NULL;
ALTER TABLE products ALTER COLUMN category DROP NOT NULL;
ALTER TABLE products ALTER COLUMN type DROP NOT NULL;
ALTER TABLE products ALTER COLUMN unit_price DROP NOT NULL;
ALTER TABLE products ALTER COLUMN cost_price DROP NOT NULL;
ALTER TABLE products ALTER COLUMN tax_rate DROP NOT NULL;
ALTER TABLE products ALTER COLUMN stock_level DROP NOT NULL;
ALTER TABLE products ALTER COLUMN reorder_point DROP NOT NULL;
ALTER TABLE products ALTER COLUMN reorder_quantity DROP NOT NULL;
ALTER TABLE products ALTER COLUMN specifications DROP NOT NULL;
ALTER TABLE products ALTER COLUMN images DROP NOT NULL;
ALTER TABLE products ALTER COLUMN dimensions DROP NOT NULL;
ALTER TABLE products ALTER COLUMN weight DROP NOT NULL;
ALTER TABLE products ALTER COLUMN manufacturer DROP NOT NULL;
ALTER TABLE products ALTER COLUMN supplier DROP NOT NULL;
ALTER TABLE products ALTER COLUMN supplier_sku DROP NOT NULL;
ALTER TABLE products ALTER COLUMN supplier_s_k_u DROP NOT NULL;
ALTER TABLE products ALTER COLUMN warranty_months DROP NOT NULL;
ALTER TABLE products ALTER COLUMN warranty_details DROP NOT NULL;
ALTER TABLE products ALTER COLUMN tags DROP NOT NULL;
ALTER TABLE products ALTER COLUMN custom_fields DROP NOT NULL;

-- SERVICES
ALTER TABLE services ALTER COLUMN code DROP NOT NULL;
ALTER TABLE services ALTER COLUMN sku DROP NOT NULL;
ALTER TABLE services ALTER COLUMN description DROP NOT NULL;
ALTER TABLE services ALTER COLUMN category DROP NOT NULL;
ALTER TABLE services ALTER COLUMN type DROP NOT NULL;
ALTER TABLE services ALTER COLUMN billing_cycle DROP NOT NULL;
ALTER TABLE services ALTER COLUMN unit_price DROP NOT NULL;
ALTER TABLE services ALTER COLUMN cost_price DROP NOT NULL;
ALTER TABLE services ALTER COLUMN tax_rate DROP NOT NULL;
ALTER TABLE services ALTER COLUMN duration_hours DROP NOT NULL;
ALTER TABLE services ALTER COLUMN duration_minutes DROP NOT NULL;
ALTER TABLE services ALTER COLUMN prerequisites DROP NOT NULL;
ALTER TABLE services ALTER COLUMN deliverables DROP NOT NULL;
ALTER TABLE services ALTER COLUMN skills_required DROP NOT NULL;
ALTER TABLE services ALTER COLUMN crew_size DROP NOT NULL;
ALTER TABLE services ALTER COLUMN equipment_needed DROP NOT NULL;
ALTER TABLE services ALTER COLUMN sla_response_hours DROP NOT NULL;
ALTER TABLE services ALTER COLUMN sla_completion_days DROP NOT NULL;
ALTER TABLE services ALTER COLUMN quality_checklist DROP NOT NULL;
ALTER TABLE services ALTER COLUMN images DROP NOT NULL;
ALTER TABLE services ALTER COLUMN tags DROP NOT NULL;
ALTER TABLE services ALTER COLUMN custom_fields DROP NOT NULL;

-- QUOTES
ALTER TABLE quotes ALTER COLUMN deal_id DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN issue_date DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN expiry_date DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN line_items DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN subtotal DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN tax_total DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN total DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN terms DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN accepted_at DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN accepted_by DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN superseded_by DROP NOT NULL;
ALTER TABLE quotes ALTER COLUMN version DROP NOT NULL;

-- INVOICES
ALTER TABLE invoices ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN deal_id DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN quote_id DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN payment_status DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN issue_date DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN invoice_date DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN due_date DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN sent_at DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN paid_at DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN line_items DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN subtotal DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN tax_total DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN total DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN amount_paid DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN balance_due DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN notes DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN terms DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN late_fee_rate DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN credits DROP NOT NULL;

-- JOBS
ALTER TABLE jobs ALTER COLUMN name DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN subject DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN description DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN assignee_id DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN crew_id DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN job_type DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN priority DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN zone DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN estimated_duration DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN scheduled_date DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN scheduled_end_date DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN completed_at DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN lat DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN lng DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN job_fields DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN swms_signed DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN completion_signature DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN evidence_photos DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN bom DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN invoice_id DROP NOT NULL;

-- CREWS
ALTER TABLE crews ALTER COLUMN leader_id DROP NOT NULL;
ALTER TABLE crews ALTER COLUMN member_ids DROP NOT NULL;
ALTER TABLE crews ALTER COLUMN color DROP NOT NULL;
ALTER TABLE crews ALTER COLUMN specialty DROP NOT NULL;
ALTER TABLE crews ALTER COLUMN status DROP NOT NULL;

-- ZONES
ALTER TABLE zones ALTER COLUMN region DROP NOT NULL;
ALTER TABLE zones ALTER COLUMN description DROP NOT NULL;
ALTER TABLE zones ALTER COLUMN color DROP NOT NULL;
ALTER TABLE zones ALTER COLUMN type DROP NOT NULL;
ALTER TABLE zones ALTER COLUMN status DROP NOT NULL;
ALTER TABLE zones ALTER COLUMN coordinates DROP NOT NULL;

-- EQUIPMENT
ALTER TABLE equipment ALTER COLUMN type DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN barcode DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN condition DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN location DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN assigned_to DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN last_service_date DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN next_service_date DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN purchase_date DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN purchase_price DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN model DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN status DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN value DROP NOT NULL;

-- INVENTORY_ITEMS
ALTER TABLE inventory_items ALTER COLUMN warehouse_qty DROP NOT NULL;
ALTER TABLE inventory_items ALTER COLUMN reorder_point DROP NOT NULL;
ALTER TABLE inventory_items ALTER COLUMN category DROP NOT NULL;
ALTER TABLE inventory_items ALTER COLUMN unit_price DROP NOT NULL;

-- WAREHOUSES
ALTER TABLE warehouses ALTER COLUMN location DROP NOT NULL;
ALTER TABLE warehouses ALTER COLUMN capacity DROP NOT NULL;
ALTER TABLE warehouses ALTER COLUMN status DROP NOT NULL;

-- PURCHASE_ORDERS
ALTER TABLE purchase_orders ALTER COLUMN supplier_id DROP NOT NULL;
ALTER TABLE purchase_orders ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE purchase_orders ALTER COLUMN items DROP NOT NULL;
ALTER TABLE purchase_orders ALTER COLUMN total DROP NOT NULL;
ALTER TABLE purchase_orders ALTER COLUMN linked_job_id DROP NOT NULL;
ALTER TABLE purchase_orders ALTER COLUMN expected_delivery DROP NOT NULL;

-- EXPENSES
ALTER TABLE expenses ALTER COLUMN vendor DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN category DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN date DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN status DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN receipt_url DROP NOT NULL;
ALTER TABLE expenses ALTER COLUMN approved_by DROP NOT NULL;

-- BANK_TRANSACTIONS
ALTER TABLE bank_transactions ALTER COLUMN date DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN description DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN type DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN status DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN match_confidence DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN matched_to_id DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN matched_to_type DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN reconciled DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN reconciled_at DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN reconciled_by DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN bank_reference DROP NOT NULL;
ALTER TABLE bank_transactions ALTER COLUMN notes DROP NOT NULL;

-- REVIEWS
ALTER TABLE reviews ALTER COLUMN author_name DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN rating DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN content DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN platform DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN status DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN replied DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN reply_content DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN replied_at DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN job_id DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN account_id DROP NOT NULL;
ALTER TABLE reviews ALTER COLUMN sentiment DROP NOT NULL;

-- USERS
ALTER TABLE users ALTER COLUMN avatar DROP NOT NULL;
ALTER TABLE users ALTER COLUMN manager_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN team DROP NOT NULL;

-- VERIFY SUCCESS
SELECT 'All NOT NULL constraints removed from optional fields' AS status;
