import React, { useMemo, useState } from 'react';
import { useCRM } from '../context/CRMContext';
import { runAudit } from '../utils/auditEngine';
import { 
  ShieldCheck, AlertTriangle, Database, Activity, 
  Settings2, Copy, Download, Link2, Search,
  Users, CheckCircle2, XCircle, FileText, Layout,
  RefreshCcw, Info, ChevronRight, Terminal, Eye,
  Target, Briefcase, Building2, User, Layers, Bug
} from 'lucide-react';
import { useLocation, useParams } from 'react-router-dom';
import { EntityType } from '../types';

const Diagnostics: React.FC = () => {
  const context = useCRM();
  const location = useLocation();
  const params = useParams();

  // --- Record Debugger State ---
  const [debugType, setDebugType] = useState<EntityType>('leads');
  const [debugId, setDebugId] = useState<string>('');

  const auditState = useMemo(() => ({
    leads: context.leads,
    deals: context.deals,
    accounts: context.accounts,
    contacts: context.contacts,
    tasks: context.tasks,
    campaigns: context.campaigns,
    tickets: context.tickets,
    invoices: context.invoices,
    subscriptions: context.subscriptions,
    documents: context.documents,
    communications: context.communications,
    users: context.users,
    settings: context.settings,
    currentUserId: context.currentUserId,
    currentUser: context.currentUser,
  }), [context]);

  const helpers = useMemo(() => ({
    getCommunicationsForEntity: context.getCommunicationsForEntity,
    canAccessRecord: context.canAccessRecord,
  }), [context]);

  const routeContext = useMemo(() => ({
    path: location.pathname,
    params: params
  }), [location, params]);

  const report = useMemo(() => runAudit(auditState, helpers, routeContext), [auditState, helpers, routeContext]);

  // --- Deep Inspector Logic ---
  const recordList = useMemo(() => {
    switch (debugType) {
      case 'leads': return context.leads;
      case 'deals': return context.deals;
      case 'accounts': return context.accounts;
      case 'contacts': return context.contacts;
      default: return [];
    }
  }, [debugType, context]);

  const inspectorData = useMemo(() => {
    if (!debugId) return null;
    
    // Raw Filter Logic (What should be found)
    const rawComms = context.communications.filter(c => c.relatedToId === debugId && c.relatedToType === debugType);
    const rawTasks = context.tasks.filter(t => t.relatedToId === debugId && t.relatedToType === debugType);
    const rawDocs = context.documents.filter(d => d.relatedToId === debugId && d.relatedToType === debugType);
    
    // Selector Logic (What context helpers return)
    const selectorComms = context.getCommunicationsForEntity(debugType, debugId);
    
    return {
      comms: { raw: rawComms, selector: selectorComms, mismatch: rawComms.length !== selectorComms.length },
      tasks: { raw: rawTasks },
      docs: { raw: rawDocs }
    };
  }, [debugId, debugType, context]);

  const [copying, setCopying] = useState(false);

  const copyMarkdown = () => {
    const md = `
# CatchaCRM System Health Report
**Timestamp:** ${report.timestamp}
**Integrity Score:** ${report.summary.integrityScore}%
**User:** ${report.personaFilters.activeUser} (${report.personaFilters.activeRole})

## Summary
- Total Checks: ${report.summary.totalChecks}
- Passed: ${report.summary.passed}
- Failed: ${report.summary.failed}

## Collection Inventory
${Object.entries(report.collections).map(([k, v]) => `- ${k}: ${v}`).join('\n')}

## Failures & Warnings
${report.failures.length > 0 ? report.failures.map(f => `- [FAIL] ${f.failureCode} on ${f.entityType}/${f.recordId}: ${f.likelyCause}`).join('\n') : '- No critical failures detected.'}

## Relationship Integrity
- Orphans Detected: ${report.relationships.orphanCount}
${report.relationships.orphans.map(o => `  - Child ${o.childId} points to missing ${o.parentType}/${o.parentId}`).join('\n')}

---
Generated by CatchaCRM Kernel Diagnostics v3.0
    `.trim();

    navigator.clipboard.writeText(md);
    setCopying(true);
    setTimeout(() => setCopying(false), 2000);
  };

  const downloadJson = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `catcha_audit_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-[1400px] mx-auto space-y-8 py-10 animate-slide-up pb-40">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row justify-between items-end gap-6">
        <div>
          <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1">System Architecture</p>
          <h1 className="text-5xl font-black text-slate-900 tracking-tight leading-none mb-1">Audit Control</h1>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={copyMarkdown}
            className="flex items-center gap-2 px-8 py-4 bg-slate-900 text-white rounded-[24px] text-[10px] font-black uppercase tracking-widest shadow-xl active:scale-95 transition-all"
          >
            {copying ? <CheckCircle2 size={16} /> : <Copy size={16} />}
            {copying ? 'Copied MD' : 'Copy MD Report'}
          </button>
          <button 
            onClick={downloadJson}
            className="flex items-center gap-2 px-8 py-4 bg-white border border-slate-200 text-slate-900 rounded-[24px] text-[10px] font-black uppercase tracking-widest shadow-lg active:scale-95 transition-all"
          >
            <Download size={16} />
            Download JSON
          </button>
        </div>
      </div>

      {/* Integrity Banner */}
      <div className={`p-10 rounded-[45px] flex items-center justify-between border shadow-2xl relative overflow-hidden ${report.summary.failed > 0 ? 'bg-rose-50 border-rose-100 text-rose-900' : 'bg-emerald-50 border-emerald-100 text-emerald-900'}`}>
        <div className="relative z-10">
          <h2 className="text-3xl font-black mb-1">{report.summary.failed > 0 ? 'Integrity Compromised' : 'System Healthy'}</h2>
          <p className="text-[10px] font-bold uppercase tracking-widest opacity-60">
            Detected {report.summary.failed} errors across {report.summary.totalChecks} automated verification checkpoints.
          </p>
          <div className="mt-8 flex gap-4">
             <div className="bg-white/40 px-6 py-2 rounded-2xl border border-white/20">
                <p className="text-[9px] font-black uppercase tracking-widest">Score</p>
                <p className="text-3xl font-black">{report.summary.integrityScore}%</p>
             </div>
             <div className="bg-white/40 px-6 py-2 rounded-2xl border border-white/20">
                <p className="text-[9px] font-black uppercase tracking-widest">Checks</p>
                <p className="text-3xl font-black">{report.summary.totalChecks}</p>
             </div>
          </div>
        </div>
        <Activity size={200} className="absolute -right-10 top-1/2 -translate-y-1/2 opacity-5 pointer-events-none" />
        {report.summary.failed > 0 ? <AlertTriangle size={80} className="relative z-10" /> : <ShieldCheck size={80} className="relative z-10" />}
      </div>

      {/* Failures Explorer */}
      {report.failures.length > 0 && (
        <div className="bg-rose-50 border border-rose-100 rounded-[40px] p-8 shadow-sm">
           <h3 className="text-xl font-black text-rose-900 mb-6 flex items-center gap-2"><Bug size={24} /> Failure Trace Log</h3>
           <div className="space-y-4">
              {report.failures.map((f, i) => (
                <div key={i} className="bg-white p-6 rounded-3xl border border-rose-200 shadow-sm flex flex-col md:flex-row gap-6">
                   <div className="md:w-1/4">
                      <p className="text-[10px] font-black text-rose-500 uppercase tracking-widest mb-1">{f.failureCode}</p>
                      <p className="text-sm font-black text-slate-900">{f.entityType.toUpperCase()} / {f.recordId}</p>
                   </div>
                   <div className="flex-1 space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                         <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
                            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Expected Outcome</p>
                            <p className="text-xs font-bold text-slate-600">{f.expected}</p>
                         </div>
                         <div className="bg-rose-50 p-3 rounded-xl border border-rose-100">
                            <p className="text-[9px] font-black text-rose-400 uppercase tracking-widest mb-1">Actual Result</p>
                            <p className="text-xs font-bold text-rose-600">{f.actual}</p>
                         </div>
                      </div>
                      <div>
                         <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Likely Root Cause</p>
                         <p className="text-sm text-slate-700 font-medium italic">{f.likelyCause}</p>
                      </div>
                   </div>
                   <div className="md:w-1/4 bg-slate-900 text-slate-400 p-4 rounded-2xl flex flex-col justify-center">
                      <p className="text-[9px] font-black uppercase mb-2">Internal Pointer</p>
                      <p className="text-[10px] font-mono leading-tight text-blue-300 break-all">{f.whereToLook}</p>
                   </div>
                </div>
              ))}
           </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Collection Grid */}
        <div className="lg:col-span-8 space-y-8">
          <div className="bg-white border border-slate-200 rounded-[40px] p-8 shadow-sm">
            <h3 className="text-xl font-black mb-8 flex items-center gap-3">
              <Database size={20} className="text-blue-600" />
              State Inventory
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {Object.entries(report.collections).map(([name, count]) => (
                <div key={name} className="p-6 bg-slate-50 border border-slate-100 rounded-3xl">
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">{name}</p>
                   <p className="text-2xl font-black text-slate-900">{count}</p>
                   <div className="mt-2 flex items-center gap-1">
                      <span className={`w-2 h-2 rounded-full ${count > 0 ? 'bg-emerald-500' : 'bg-rose-500'}`}></span>
                      <span className="text-[9px] font-bold text-slate-400 uppercase">{count > 0 ? 'Seeded' : 'Empty'}</span>
                   </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-[40px] p-8 shadow-sm">
            <h3 className="text-xl font-black mb-8 flex items-center gap-3">
              <Link2 size={20} className="text-amber-500" />
              Relational Integrity
            </h3>
            <div className="space-y-4">
               {report.relationships.orphans.length === 0 && report.relationships.casingIssues.length === 0 ? (
                 <div className="py-10 text-center text-slate-300 font-black uppercase text-xs tracking-widest flex flex-col items-center gap-3">
                    <CheckCircle2 size={32} className="text-emerald-500 opacity-50" />
                    No orphans detected
                 </div>
               ) : (
                 <div className="space-y-3">
                    {report.relationships.orphans.map((o, i) => (
                      <div key={i} className="p-4 bg-rose-50 border border-rose-100 rounded-2xl flex items-center justify-between">
                         <div className="flex items-center gap-3">
                            <XCircle size={14} className="text-rose-500" />
                            <p className="text-xs font-bold text-rose-900">
                               <span className="uppercase font-black">{o.childType}</span> {o.childId} points to non-existent <span className="uppercase font-black">{o.parentType}</span> {o.parentId}
                            </p>
                         </div>
                         <span className="text-[9px] font-black bg-rose-100 text-rose-700 px-2 py-1 rounded-lg uppercase">Orphan</span>
                      </div>
                    ))}
                 </div>
               )}
            </div>
          </div>

          {/* Record Deep Inspector Dropdowns */}
          <div className="bg-slate-50 border border-slate-200 rounded-[45px] p-10 shadow-sm">
             <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-10">
                <div className="flex items-center gap-3">
                   <div className="p-3 bg-blue-600 text-white rounded-2xl shadow-lg shadow-blue-200">
                      <Eye size={24} />
                   </div>
                   <div>
                      <h3 className="text-2xl font-black text-slate-900 tracking-tight">Record Logic Inspector</h3>
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Identify why related records fail to appear in tabs.</p>
                   </div>
                </div>
                <div className="flex gap-2 w-full md:w-auto">
                   <select 
                      value={debugType} 
                      onChange={(e) => { setDebugType(e.target.value as EntityType); setDebugId(''); }}
                      className="bg-white border border-slate-200 rounded-xl px-4 py-3 text-xs font-black uppercase tracking-widest focus:outline-none shadow-sm"
                   >
                      <option value="leads">Leads</option>
                      <option value="accounts">Accounts</option>
                      <option value="contacts">Contacts</option>
                      <option value="deals">Deals</option>
                   </select>
                   <select 
                      value={debugId} 
                      onChange={(e) => setDebugId(e.target.value)}
                      className="bg-white border border-slate-200 rounded-xl px-4 py-3 text-xs font-black uppercase tracking-widest focus:outline-none shadow-sm min-w-[200px]"
                   >
                      <option value="">Select Record...</option>
                      {recordList.map(r => (
                        <option key={r.id} value={r.id}>{r.name || (r as any).company} ({r.id})</option>
                      ))}
                   </select>
                </div>
             </div>

             {debugId && inspectorData ? (
               <div className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                     <InspectorCard 
                        label="Communications" 
                        rawCount={inspectorData.comms.raw.length} 
                        selectorCount={inspectorData.comms.selector.length}
                        mismatch={inspectorData.comms.mismatch}
                        rawIds={inspectorData.comms.raw.map(c => c.id)}
                     />
                     <InspectorCard 
                        label="Tasks" 
                        rawCount={inspectorData.tasks.raw.length} 
                        selectorCount={null}
                        rawIds={inspectorData.tasks.raw.map(t => t.id)}
                     />
                     <InspectorCard 
                        label="Documents" 
                        rawCount={inspectorData.docs.raw.length} 
                        selectorCount={null}
                        rawIds={inspectorData.docs.raw.map(d => d.id)}
                     />
                  </div>
                  
                  <div className="p-6 bg-white rounded-3xl border border-slate-200">
                     <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Relational Proof (Raw State)</p>
                     <div className="flex flex-wrap gap-2">
                        {inspectorData.comms.raw.map(c => (
                          <span key={c.id} className="px-3 py-1 bg-blue-50 text-blue-600 rounded-lg text-[10px] font-black border border-blue-100">COMM: {c.id}</span>
                        ))}
                        {inspectorData.tasks.raw.map(t => (
                          <span key={t.id} className="px-3 py-1 bg-emerald-50 text-emerald-600 rounded-lg text-[10px] font-black border border-emerald-100">TASK: {t.id}</span>
                        ))}
                        {inspectorData.docs.raw.map(d => (
                          <span key={d.id} className="px-3 py-1 bg-amber-50 text-amber-600 rounded-lg text-[10px] font-black border border-amber-100">DOC: {d.id}</span>
                        ))}
                        {![...inspectorData.comms.raw, ...inspectorData.tasks.raw, ...inspectorData.docs.raw].length && (
                           <p className="text-xs text-slate-300 italic font-bold">No child records linked to this entity in raw state.</p>
                        )}
                     </div>
                  </div>
               </div>
             ) : (
               <div className="py-20 flex flex-col items-center justify-center text-slate-300">
                  <Layers size={48} strokeWidth={1} className="opacity-20 mb-4" />
                  <p className="text-[10px] font-black uppercase tracking-[0.2em]">Select a record to initiate deep inspection</p>
               </div>
             )}
          </div>
        </div>

        {/* Sidebar Diagnostics */}
        <div className="lg:col-span-4 space-y-8">
          <div className="bg-slate-900 rounded-[40px] p-8 text-white shadow-xl">
            <h3 className="text-lg font-black mb-6 flex items-center gap-3 text-blue-400">
              <Terminal size={18} />
              Persona Session
            </h3>
            <div className="space-y-6">
              <div>
                <p className="text-[9px] font-black uppercase text-slate-500 tracking-widest mb-2">Active User Identity</p>
                <div className="flex items-center gap-3">
                   <div className="w-10 h-10 rounded-xl bg-slate-800 flex items-center justify-center border border-slate-700">
                      <Users size={18} className="text-blue-400" />
                   </div>
                   <div>
                      <p className="text-sm font-black text-white leading-none mb-1">{report.personaFilters.activeUser}</p>
                      <p className="text-[9px] font-bold text-blue-400 uppercase tracking-widest">{report.personaFilters.activeRole} PERMISSIONS</p>
                   </div>
                </div>
              </div>
              
              <div className="pt-6 border-t border-slate-800">
                <p className="text-[9px] font-black uppercase text-slate-500 tracking-widest mb-4">Hierarchical Visibility Impact</p>
                <div className="space-y-4">
                   {Object.entries(report.personaFilters.impactByCollection).map(([type, stats]) => (
                     <div key={type} className="flex items-center justify-between">
                        <span className="text-[10px] font-bold text-slate-400 uppercase">{type}</span>
                        <div className="flex items-center gap-3">
                           <span className="text-[10px] font-black text-emerald-400">{stats.visible} Visible</span>
                           <span className="text-[10px] font-black text-rose-400">{stats.hidden} Hidden</span>
                        </div>
                     </div>
                   ))}
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-[40px] p-8 shadow-sm">
            <h3 className="text-xl font-black mb-6 flex items-center gap-3">
              <Settings2 size={20} className="text-slate-400" />
              Settings Health
            </h3>
            <div className="space-y-3">
              {Object.entries(report.settings.checks).map(([key, check]) => (
                <div key={key} className="flex items-center justify-between p-3 bg-slate-50 rounded-2xl border border-slate-100">
                   <span className="text-[10px] font-black uppercase text-slate-600 tracking-tighter">{key}</span>
                   {check.ok ? <CheckCircle2 size={14} className="text-emerald-500" /> : <XCircle size={14} className="text-rose-500" />}
                </div>
              ))}
            </div>
            {report.failures.some(f => f.failureCode === 'SETTINGS_WIPE') && (
               <div className="mt-6 p-4 bg-rose-50 border border-rose-100 rounded-2xl">
                  <p className="text-[9px] font-black uppercase text-rose-600 mb-1 flex items-center gap-1"><AlertTriangle size={10} /> Configuration Issue</p>
                  <p className="text-[10px] font-bold text-rose-800 leading-relaxed">Required dictionaries are missing or blank. User experience will be degraded.</p>
               </div>
            )}
          </div>

          <div className="bg-blue-50 border border-blue-100 rounded-[40px] p-8">
             <h3 className="text-lg font-black text-blue-900 mb-2 flex items-center gap-2">
                <RefreshCcw size={18} />
                Kernel Bootstrap
             </h3>
             <p className="text-[10px] font-bold text-blue-700 uppercase tracking-widest mb-6">Status: {report.seedIntegrity.status}</p>
             <div className="space-y-4">
                <button 
                  onClick={() => context.resetDemoData()}
                  className="w-full py-4 bg-blue-600 text-white rounded-2xl text-[9px] font-black uppercase tracking-[0.2em] shadow-lg shadow-blue-200 active:scale-95 transition-all"
                >
                   Force Re-Seed Dictionaries
                </button>
                <p className="text-[9px] text-blue-600/60 text-center font-bold px-4 leading-relaxed italic">Wipe dictionaries only. Persistence of Leads and Deals is managed via individual record actions.</p>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const InspectorCard = ({ label, rawCount, selectorCount, mismatch, rawIds }: any) => (
  <div className={`p-6 rounded-[30px] border shadow-sm transition-all ${mismatch ? 'bg-rose-50 border-rose-100' : 'bg-white border-slate-100'}`}>
     <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">{label}</p>
     <div className="flex justify-between items-end">
        <div>
           <p className="text-[9px] font-black text-slate-400 uppercase">State Raw</p>
           <p className="text-3xl font-black text-slate-900">{rawCount}</p>
        </div>
        {selectorCount !== null && (
           <div className="text-right">
              <p className="text-[9px] font-black text-slate-400 uppercase">Tab Selector</p>
              <p className={`text-3xl font-black ${mismatch ? 'text-rose-600' : 'text-emerald-600'}`}>{selectorCount}</p>
           </div>
        )}
     </div>
     {mismatch && (
        <div className="mt-4 pt-4 border-t border-rose-100 flex items-center gap-2 text-rose-600">
           <AlertTriangle size={14} />
           <p className="text-[9px] font-black uppercase">Logic Discrepancy Detected</p>
        </div>
     )}
  </div>
);

export default Diagnostics;